In [18]:
import pandas as pd 
import numpy as np 
import yfinance as yf 
import plotly.graph_objects as go
from datetime import datetime

# MemeStonks

In [22]:
# Downloading Historical MemeStonks
memestocks = yf.download('GME BB AMC', start="2020-09-01", end="2021-04-01", group_by='tickers', interval ='60m', tz='CET')
memestocks = memestocks.reset_index(level=['Datetime'])
memestocks.head()

[*********************100%***********************]  3 of 3 completed

                   Datetime     GME                                          \
                               Open  High   Low  Close Adj Close     Volume
0 2020-09-01 09:30:00-04:00  7.3000  7.49  6.77  7.165     7.165  6195127.0
1 2020-09-01 10:30:00-04:00  7.1650  7.62  7.14  7.245     7.245  4164376.0
2 2020-09-01 11:30:00-04:00  7.2400  7.44  7.02  7.430     7.430  1968057.0
3 2020-09-01 12:30:00-04:00  7.4278  7.70  7.37  7.490     7.490  3054700.0
4 2020-09-01 13:30:00-04:00  7.4900  7.56  7.32  7.465     7.465  2021132.0

       BB                                               AMC               \
     Open  High    Low   Close Adj Close     Volume    Open  High    Low
0  5.2500  5.51  5.210  5.5099    5.5099  1557090.0  5.7900  6.18  5.790
1  5.5000  5.51  5.400  5.4250    5.4250   920134.0  6.0800  6.15  5.980
2  5.4211  5.49  5.420  5.4400    5.4400   635989.0  6.0200  6.09  5.928
3  5.4400  5.47  5.420  5.4650    5.4650   860373.0  5.9879  6.03  5.970
4  5.4641  5.48  5.438  5.4750    5.4750   534820.0  6.0150  6.13  5.970


    Close Adj Close     Volume
0  6.0880    6.0880  1935732.0
1  6.0250    6.0250   948528.0
2  5.9850    5.9850   545432.0
3  6.0150    6.0150   296193.0
4  6.1121    6.1121   788023.0

# MemePlot